package com.example.data

object CartoonRepository {

    val sampleCartoons = listOf(
        CartoonItem(
            id = "c1",
            title = "Yellow Mascot Adventures S1",
            genre = "Animation / Comedy / Adventure",
            rating = "9.9 IMDB",
            year = "2026",
            language = "en",
            posterUrl = "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            description = "The cheerful Yellow Mascot travels across magical cartoon realms, discovering live IPTV channels and retro animated treasures!",
            source = "YellowCartoon Original",
            isFeatured = true,
            episodes = listOf(
                EpisodeItem(1, "The Great Yellow Spark", "11:20", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"),
                EpisodeItem(2, "IPTV Channel Quest", "10:45", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"),
                EpisodeItem(3, "Torrent P2P Speedrun", "12:10", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4")
            )
        ),
        CartoonItem(
            id = "c2",
            title = "Retro Toon Arcade (KissCartoon Vault)",
            genre = "Classic Animation / Slapstick",
            rating = "9.6 IMDB",
            year = "1998",
            language = "en",
            posterUrl = "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            description = "High-definition remaster of classic Saturday morning cartoon adventures inspired by KissCartoon archives.",
            source = "KissCartoon Archives",
            isFeatured = true
        ),
        CartoonItem(
            id = "c3",
            title = "Dragon Cyber Quest (Anime)",
            genre = "Anime / Action / Sci-Fi",
            rating = "9.7 IMDB",
            year = "2025",
            language = "es",
            posterUrl = "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            description = "Un grupo de jóvenes héroes se embarcan en un viaje cibernético para salvar el universo del anime.",
            source = "BiliBili / CrunchyVault",
            isFeatured = true
        ),
        CartoonItem(
            id = "c4",
            title = "YouTube Kids Fun Learningland",
            genre = "Kids / Songs / Preschool",
            rating = "9.4 IMDB",
            year = "2026",
            language = "pt",
            posterUrl = "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
            description = "Desenhos educativos coloridos com canções infantis e histórias divertidas para crianças de todas as idades.",
            source = "YouTube Kids",
            isFeatured = false
        ),
        CartoonItem(
            id = "c5",
            title = "Sora 2 AI Lost Media Artifacts",
            genre = "AI Cinema / Surreal Animation",
            rating = "9.9 TMDB",
            year = "2026",
            language = "en",
            posterUrl = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyplays.mp4",
            description = "Archived lost media renders generated by Sora 2 AI, featuring hyper-detailed 3D cartoon worlds.",
            source = "Sora 2 AI Vault",
            isFeatured = true
        ),
        CartoonItem(
            id = "c6",
            title = "DangoPlayer IPTV Cinema Express",
            genre = "Live Cartoon Streams",
            rating = "9.5 IMDB",
            year = "2026",
            language = "es",
            posterUrl = "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80",
            videoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
            description = "Canal de streaming ininterrumpido de películas animadas clásicas y contemporáneas en español y portugués.",
            source = "DangoPlayer IPTV",
            isFeatured = false
        )
    )

    val sampleIptvChannels = listOf(
        IptvChannel("iptv_1", "Yellow Toons 24/7", "https://img.icons8.com/color/96/cartoon.png", "Animation & Kids", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", "Global"),
        IptvChannel("iptv_2", "KissCartoon TV Live", "https://img.icons8.com/color/96/retro-tv.png", "Classic Cartoons", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4", "USA"),
        IptvChannel("iptv_3", "Anime Central HD", "https://img.icons8.com/color/96/dragon.png", "Anime", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", "Japan"),
        IptvChannel("iptv_4", "TDT Kids España", "https://img.icons8.com/color/96/spain.png", "Infantil", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4", "Spain"),
        IptvChannel("iptv_5", "Desenhos Brasil TV", "https://img.icons8.com/color/96/brazil.png", "Infantil BR", "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4", "Brazil")
    )

    val sampleTorrents = listOf(
        TorrentStream("tor_1", "YellowCartoon.Collection.2026.1080p.P2P.mkv", "magnet:?xt=urn:btih:123456789abcdef0123456789abcdef012345678&dn=YellowCartoon2026", "Cartoons", "1080p Web-DL", "4.2 GB", 1840, 120),
        TorrentStream("tor_2", "KissCartoon.Classics.Archive.720p.Torrent", "magnet:?xt=urn:btih:abcdef1234567890abcdef1234567890abcdef12&dn=KissCartoonClassics", "Classic Toons", "720p Remux", "8.9 GB", 2450, 310),
        TorrentStream("tor_3", "Sora2.AI.Lost.Media.4K.HDR.x265", "magnet:?xt=urn:btih:9876543210fedcba9876543210fedcba98765432&dn=Sora2AILostMedia4K", "AI Lost Media", "4K HDR", "12.5 GB", 3890, 450)
    )

    val sampleSpotifyTracks = listOf(
        SpotifyTrack("sp_1", "Cartoon Main Theme (Yellow TV)", "Yellow Cartoon Orchestra", "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&q=80", "https://open.spotify.com/embed/track/4cOdK2wGLETKBW3PvgPWqT", "3:45"),
        SpotifyTrack("sp_2", "Anime Battle Energy OST", "Tokyo Toon Beats", "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&q=80", "https://open.spotify.com/embed/track/3n3Lp6lH8v3PvgPWqT", "2:50"),
        SpotifyTrack("sp_3", "Kids Lullaby & Bedtime Songs", "Sweet Yellow Dreams", "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=500&q=80", "https://open.spotify.com/embed/track/1a2b3c4d5e6f7g8h9i0j", "4:15")
    )
}
